import { Link } from 'react-router-dom';
import { MessageSquare, ArrowLeft } from 'lucide-react';
import { useTranslation } from '../hooks/useTranslation';

export function Terms() {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-4">
        <div className="container mx-auto flex items-center gap-4">
          <Link
            to="/"
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            <ArrowLeft size={20} className="text-gray-600 dark:text-gray-400" />
          </Link>
          <MessageSquare className="w-6 h-6 text-teal-600 dark:text-teal-400" />
          <h1 className="text-xl font-semibold text-gray-900 dark:text-white">
            {t('navigation.terms')}
          </h1>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-8">
          <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-4">
            Terms of Service
          </h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">
            Last updated: January 2024
          </p>

          <div className="prose dark:prose-invert max-w-none space-y-6">
            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                1. Acceptance of Terms
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                By accessing and using AIMAI, you accept and agree to be bound by these Terms of
                Service. If you do not agree to these terms, please do not use our service.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                2. Description of Service
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                AIMAI is an AI-powered assistant service provided by Trans-Nzoia County Government
                to help residents access information about county services. The service is provided
                "as is" and may be modified or discontinued at any time.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                3. Acceptable Use
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                You agree to use AIMAI only for lawful purposes. You must not:
              </p>
              <ul className="list-disc list-inside text-gray-600 dark:text-gray-300 space-y-2 ml-4">
                <li>Use the service to transmit harmful, illegal, or offensive content</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Use automated systems to access the service without permission</li>
                <li>Impersonate others or provide false information</li>
                <li>Interfere with or disrupt the service</li>
              </ul>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                4. User Accounts
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activities that occur under your account. You must notify us
                immediately of any unauthorized use of your account.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                5. Content and Accuracy
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                While we strive to provide accurate information, AIMAI's responses are generated by
                AI and may contain errors. Always verify important information through official
                county channels. We are not responsible for decisions made based on information
                provided by AIMAI.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                6. Intellectual Property
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                The AIMAI service, including its design, functionality, and content, is owned by
                Trans-Nzoia County Government and is protected by intellectual property laws. You
                may not copy, modify, or distribute any part of the service without permission.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                7. Privacy
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Your use of AIMAI is subject to our Privacy Policy, which describes how we collect,
                use, and protect your personal information. By using AIMAI, you consent to our
                privacy practices.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                8. Limitation of Liability
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Trans-Nzoia County Government shall not be liable for any indirect, incidental,
                special, consequential, or punitive damages resulting from your use of or inability
                to use AIMAI, even if we have been advised of the possibility of such damages.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                9. Service Availability
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We do not guarantee that AIMAI will be available at all times. The service may be
                interrupted for maintenance, updates, or due to factors beyond our control.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                10. Termination
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We reserve the right to suspend or terminate your access to AIMAI at any time,
                without notice, for any reason, including violation of these Terms of Service.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                11. Changes to Terms
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                We may modify these Terms of Service at any time. Continued use of AIMAI after
                changes constitutes acceptance of the modified terms.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                12. Governing Law
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                These Terms of Service are governed by the laws of Kenya. Any disputes shall be
                resolved in the courts of Kenya.
              </p>
            </section>

            <section>
              <h3 className="text-2xl font-semibold text-gray-900 dark:text-white mb-3">
                13. Contact Information
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                For questions about these Terms of Service, contact:
              </p>
              <ul className="list-none text-gray-600 dark:text-gray-300 space-y-2 ml-4 mt-2">
                <li>Email: legal@aimai.transnzoia.go.ke</li>
                <li>Phone: +254 712 345 678</li>
                <li>Address: Trans-Nzoia County Government, Kitale, Kenya</li>
              </ul>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
